
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE billing CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE appointments CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE treatments CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE dentists CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE patients CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE patients (
    patient_id NUMBER PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    phone VARCHAR2(15),
    email VARCHAR2(100),
    address VARCHAR2(255),
    created_at DATE DEFAULT SYSDATE
);


CREATE TABLE dentists (
    dentist_id NUMBER PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    specialization VARCHAR2(100),
    phone VARCHAR2(15),
    email VARCHAR2(100)
);

CREATE TABLE treatments (
    treatment_id NUMBER PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    cost NUMBER(10,2)
);

CREATE TABLE appointments (
    appointment_id NUMBER PRIMARY KEY,
    patient_id NUMBER REFERENCES patients(patient_id),
    dentist_id NUMBER REFERENCES dentists(dentist_id),
    treatment_id NUMBER REFERENCES treatments(treatment_id),
    appointment_date DATE NOT NULL,
    status VARCHAR2(20) DEFAULT 'Scheduled'
);

CREATE TABLE billing (
    billing_id NUMBER PRIMARY KEY,
    appointment_id NUMBER REFERENCES appointments(appointment_id),
    amount NUMBER(10,2),
    payment_status VARCHAR2(20) DEFAULT 'Pending',
    billed_at DATE DEFAULT SYSDATE
);


CREATE TABLE patient_audit (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER NOT NULL,
    action VARCHAR2(20) NOT NULL,
    action_time DATE NOT NULL
);

COMMIT;

